# Generated by Django 2.2.10 on 2020-03-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Smaagam',
            fields=[
                ('smaagam_id', models.AutoField(primary_key=True, serialize=False)),
                ('smaagam_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kirtan',
            fields=[
                ('kirtan_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirtan.Artist')),
                ('smaagam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirtan.Smaagam')),
            ],
        ),
    ]
